import turtle 
def draw_circle ():
#import twilio
    window = turtle.Screen()

    window.bgcolor("black")

    brad = turtle.Turtle()
    brad.color("white")
    #brad.forward(200)
    brad.shape("turtle")
    #for i in range (5):
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    brad.circle(100)
    brad.right(15)
    

    window.exitonclick()

draw_circle ()  
